"""
pdf_reports.py — PDF generation for ADMRS
Generates Mission Briefs and Monthly Impact Reports using reportlab.
Falls back to plain-text bytes if reportlab not installed.
"""
from datetime import datetime
from pathlib import Path
import io

# ── Try reportlab, fall back to text ──────────────────────────────
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, HRFlowable)
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

# ── Colour palette ─────────────────────────────────────────────────
C_BG      = colors.HexColor("#0b0e17")
C_DARK    = colors.HexColor("#0e1420")
C_GREEN   = colors.HexColor("#3fb950")
C_RED     = colors.HexColor("#f85149")
C_AMBER   = colors.HexColor("#d29922")
C_BLUE    = colors.HexColor("#58a6ff")
C_LIGHT   = colors.HexColor("#e6edf3")
C_MUTED   = colors.HexColor("#8892a4")
C_BORDER  = colors.HexColor("#1a2035")


def _text_mission_brief(alert_id, sector, lat, lon, ha, confidence,
                         ranger, co2_t, cause, now_str) -> bytes:
    lines = [
        "=" * 62,
        "  ADMRS — RANGER MISSION BRIEF",
        "=" * 62,
        f"  Generated : {now_str} UTC",
        f"  Alert ID  : {alert_id}",
        f"  Ranger    : {ranger}",
        "-" * 62,
        "  OPERATIONAL DETAILS",
        "-" * 62,
        f"  Sector      : {sector}",
        f"  Coordinates : {lat:.5f}°N, {lon:.5f}°W",
        f"  Google Maps : https://maps.google.com/?q={lat},{lon}",
        f"  GEE Link    : https://code.earthengine.google.com/?q={lat},{lon}",
        f"  Area Lost   : {ha:.1f} ha",
        f"  AI Conf.    : {confidence:.0%}",
        f"  Est. Cause  : {cause}",
        f"  CO₂ Impact  : {co2_t:,.0f} tonnes",
        "-" * 62,
        "  MISSION OBJECTIVES",
        "-" * 62,
        "  1. Reach designated coordinates and document evidence",
        "  2. Photograph deforestation boundary markers",
        "  3. Identify machinery, vehicles, or personnel",
        "  4. Collect GPS waypoints at active clearing edge",
        "  5. Report findings via SMS/field app within 4 hours",
        "-" * 62,
        "  SAFETY PROTOCOLS",
        "-" * 62,
        "  · Operate in pairs — do not enter alone",
        "  · Carry emergency beacon at all times",
        "  · Check in every 60 minutes via satellite phone",
        "  · Abort if armed activity detected — call HQ",
        "=" * 62,
        "  AUTHORISED — ADMRS Operations Command",
        "=" * 62,
    ]
    return "\n".join(lines).encode("utf-8")


def _text_monthly_report(stats: dict) -> bytes:
    lines = [
        "=" * 62,
        "  ADMRS — MONTHLY IMPACT REPORT",
        "=" * 62,
        f"  Period  : {stats.get('period','Last 30 Days')}",
        f"  Generated : {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
        "-" * 62,
        "  FOREST PROTECTION SUMMARY",
        "-" * 62,
        f"  Hectares Monitored  : {stats.get('ha_monitored',1_200_000):,} ha",
        f"  Forest Loss Detected: {stats.get('ha_lost',0):.1f} ha",
        f"  Alerts Generated    : {stats.get('n_alerts',0)}",
        f"  Critical Alerts     : {stats.get('n_critical',0)}",
        f"  Alerts Validated    : {stats.get('n_validated',0)}",
        f"  False Positive Rate : {stats.get('fp_rate',8.2):.1f}%",
        "-" * 62,
        "  CARBON IMPACT",
        "-" * 62,
        f"  CO₂ Emissions Prevented : {stats.get('co2_prevented',0):,.0f} t",
        f"  Carbon Credits Est.     : {stats.get('credits',0):,.0f} VCUs",
        f"  Est. Market Value       : ${stats.get('usd_value',0):,.0f}",
        "-" * 62,
        "  RANGER OPERATIONS",
        "-" * 62,
        f"  Dispatches              : {stats.get('dispatched',0)}",
        f"  Avg Response Time       : {stats.get('avg_response','2h 15m')}",
        f"  Field Verification Rate : {stats.get('verify_rate',92)}%",
        f"  Evidence Photos Upload  : {stats.get('n_evidence',0)}",
        "=" * 62,
        "  Report generated by ADMRS v4.0",
        "=" * 62,
    ]
    return "\n".join(lines).encode("utf-8")


def generate_mission_brief(alert_id, sector, lat, lon, ha, confidence,
                            ranger, co2_t, cause="Illegal logging") -> bytes:
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M")

    if not HAS_REPORTLAB:
        return _text_mission_brief(alert_id, sector, lat, lon, ha,
                                   confidence, ranger, co2_t, cause, now_str)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                             leftMargin=1.8*cm, rightMargin=1.8*cm,
                             topMargin=1.5*cm, bottomMargin=1.5*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", fontSize=16, textColor=C_GREEN,
                                  fontName="Helvetica-Bold", alignment=TA_CENTER,
                                  spaceAfter=4)
    sub_style   = ParagraphStyle("sub", fontSize=8, textColor=C_MUTED,
                                  fontName="Helvetica", alignment=TA_CENTER,
                                  spaceAfter=12)
    head_style  = ParagraphStyle("head", fontSize=9, textColor=C_GREEN,
                                  fontName="Helvetica-Bold", spaceBefore=10,
                                  spaceAfter=4, textTransform="uppercase")
    body_style  = ParagraphStyle("body", fontSize=9, textColor=C_LIGHT,
                                  fontName="Helvetica", leading=14)
    mono_style  = ParagraphStyle("mono", fontSize=8, textColor=C_BLUE,
                                  fontName="Courier", leading=12)

    elems = []

    # ── Header ──
    elems.append(Paragraph("🛰 ADMRS", title_style))
    elems.append(Paragraph("RANGER MISSION BRIEF — CONFIDENTIAL", sub_style))
    elems.append(HRFlowable(width="100%", thickness=1, color=C_GREEN, spaceAfter=8))

    # ── Meta table ──
    meta = [
        ["Generated", now_str + " UTC", "Alert ID", alert_id],
        ["Ranger",    ranger,           "Status",   "ACTIVE DEPLOYMENT"],
    ]
    t = Table(meta, colWidths=[3*cm, 6.5*cm, 3*cm, 6.5*cm])
    t.setStyle(TableStyle([
        ("FONTNAME",    (0,0),(-1,-1), "Helvetica"),
        ("FONTSIZE",    (0,0),(-1,-1), 8),
        ("TEXTCOLOR",   (0,0),(0,-1),  C_MUTED),
        ("TEXTCOLOR",   (2,0),(2,-1),  C_MUTED),
        ("TEXTCOLOR",   (1,0),(1,-1),  C_LIGHT),
        ("TEXTCOLOR",   (3,0),(3,-1),  C_GREEN),
        ("FONTNAME",    (3,1),(3,1),   "Helvetica-Bold"),
        ("BACKGROUND",  (0,0),(-1,-1), C_DARK),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[C_DARK, C_BG]),
        ("GRID",        (0,0),(-1,-1), 0.5, C_BORDER),
        ("TOPPADDING",  (0,0),(-1,-1), 5),
        ("BOTTOMPADDING",(0,0),(-1,-1),5),
        ("LEFTPADDING", (0,0),(-1,-1), 6),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 8))

    # ── Operational details ──
    elems.append(Paragraph("◈ OPERATIONAL DETAILS", head_style))
    gmap = f"https://maps.google.com/?q={lat},{lon}"
    gee  = f"https://code.earthengine.google.com/"
    ops_data = [
        ["Sector",           sector,        "Area Lost",      f"{ha:.1f} ha"],
        ["Coordinates",      f"{lat:.5f}°N {lon:.5f}°W", "AI Confidence", f"{confidence:.0%}"],
        ["Est. Cause",       cause,         "CO₂ Impact",     f"{co2_t:,.0f} tonnes"],
        ["Google Maps",      gmap,          "Earth Engine",   gee],
    ]
    t2 = Table(ops_data, colWidths=[3*cm, 6.5*cm, 3*cm, 6.5*cm])
    t2.setStyle(TableStyle([
        ("FONTNAME",    (0,0),(-1,-1), "Helvetica"),
        ("FONTSIZE",    (0,0),(-1,-1), 8),
        ("TEXTCOLOR",   (0,0),(0,-1),  C_MUTED),
        ("TEXTCOLOR",   (2,0),(2,-1),  C_MUTED),
        ("TEXTCOLOR",   (1,0),(1,-1),  C_LIGHT),
        ("TEXTCOLOR",   (3,0),(3,-1),  C_AMBER),
        ("FONTNAME",    (1,2),(1,2),   "Helvetica-Bold"),
        ("BACKGROUND",  (0,0),(-1,-1), C_DARK),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[C_DARK, C_BG]),
        ("GRID",        (0,0),(-1,-1), 0.5, C_BORDER),
        ("TOPPADDING",  (0,0),(-1,-1), 5),
        ("BOTTOMPADDING",(0,0),(-1,-1),5),
        ("LEFTPADDING", (0,0),(-1,-1), 6),
        ("WORDWRAP",    (0,0),(-1,-1), True),
    ]))
    elems.append(t2)
    elems.append(Spacer(1, 8))

    # ── Objectives ──
    elems.append(Paragraph("◈ MISSION OBJECTIVES", head_style))
    objectives = [
        "1.  Reach designated coordinates and document site evidence with photos.",
        "2.  Photograph deforestation boundary markers and active clearing edge.",
        "3.  Identify and record machinery, vehicles, or personnel present.",
        "4.  Collect GPS waypoints at perimeter — minimum 4 corner points.",
        "5.  Submit field report via ADMRS app within 4 hours of arrival.",
    ]
    for obj in objectives:
        elems.append(Paragraph(obj, body_style))
    elems.append(Spacer(1, 8))

    # ── Safety ──
    elems.append(Paragraph("◈ SAFETY PROTOCOLS", head_style))
    safety = [
        "·  Operate in pairs — do not enter sector alone under any circumstances.",
        "·  Carry emergency beacon; check in via satellite phone every 60 minutes.",
        "·  If armed activity detected: abort immediately, do not engage, call HQ.",
        "·  Weather abort threshold: visibility < 200 m or wind speed > 40 km/h.",
    ]
    for s in safety:
        elems.append(Paragraph(s, body_style))

    elems.append(Spacer(1, 12))
    elems.append(HRFlowable(width="100%", thickness=1, color=C_GREEN))
    elems.append(Spacer(1, 4))
    elems.append(Paragraph(
        "AUTHORISED — ADMRS Operations Command · v4.0",
        ParagraphStyle("auth", fontSize=8, textColor=C_GREEN,
                       fontName="Helvetica-Bold", alignment=TA_CENTER)))

    doc.build(elems)
    buf.seek(0)
    return buf.read()


def generate_monthly_report(stats: dict) -> bytes:
    if not HAS_REPORTLAB:
        return _text_monthly_report(stats)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                             leftMargin=1.8*cm, rightMargin=1.8*cm,
                             topMargin=1.5*cm, bottomMargin=1.5*cm)
    styles = getSampleStyleSheet()

    title_s = ParagraphStyle("t", fontSize=17, textColor=C_GREEN,
                              fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=4)
    sub_s   = ParagraphStyle("s", fontSize=8, textColor=C_MUTED,
                              fontName="Helvetica", alignment=TA_CENTER, spaceAfter=12)
    head_s  = ParagraphStyle("h", fontSize=9, textColor=C_GREEN,
                              fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=5)
    val_s   = ParagraphStyle("v", fontSize=22, textColor=C_LIGHT,
                              fontName="Helvetica-Bold", alignment=TA_CENTER)
    lbl_s   = ParagraphStyle("l", fontSize=7, textColor=C_MUTED,
                              fontName="Helvetica", alignment=TA_CENTER)

    elems = []
    elems.append(Paragraph("🛰 ADMRS", title_s))
    elems.append(Paragraph(f"MONTHLY IMPACT REPORT — {stats.get('period','LAST 30 DAYS').upper()}", sub_s))
    elems.append(HRFlowable(width="100%", thickness=1, color=C_GREEN, spaceAfter=10))

    # KPI summary row
    kpi_vals = [
        [Paragraph(f"{stats.get('ha_lost',0):.1f}", val_s),
         Paragraph(f"{stats.get('n_alerts',0)}", val_s),
         Paragraph(f"{stats.get('co2_prevented',0):,.0f}", val_s),
         Paragraph(f"${stats.get('usd_value',0):,.0f}", val_s)],
        [Paragraph("Hectares Lost", lbl_s),
         Paragraph("Alerts", lbl_s),
         Paragraph("CO₂ Tonnes Prevented", lbl_s),
         Paragraph("Est. Carbon Value", lbl_s)],
    ]
    kt = Table(kpi_vals, colWidths=[4.7*cm]*4)
    kt.setStyle(TableStyle([
        ("BACKGROUND",     (0,0),(-1,-1), C_DARK),
        ("GRID",           (0,0),(-1,-1), 0.5, C_BORDER),
        ("TOPPADDING",     (0,0),(-1,-1), 10),
        ("BOTTOMPADDING",  (0,0),(-1,-1), 10),
        ("TEXTCOLOR",      (0,0),(0,0),   C_RED),
        ("TEXTCOLOR",      (1,0),(1,0),   C_AMBER),
        ("TEXTCOLOR",      (2,0),(2,0),   C_GREEN),
        ("TEXTCOLOR",      (3,0),(3,0),   C_BLUE),
    ]))
    elems.append(kt)
    elems.append(Spacer(1, 10))

    # Sections
    for section_title, rows in [
        ("◈ FOREST PROTECTION", [
            ("Hectares Monitored",  f"{stats.get('ha_monitored',1_200_000):,} ha"),
            ("Forest Loss",         f"{stats.get('ha_lost',0):.1f} ha"),
            ("Alerts Generated",    str(stats.get('n_alerts',0))),
            ("Critical Alerts",     str(stats.get('n_critical',0))),
            ("Validated Alerts",    str(stats.get('n_validated',0))),
            ("False Positive Rate", f"{stats.get('fp_rate',8.2):.1f}%"),
        ]),
        ("◈ CARBON ACCOUNTING", [
            ("CO₂ Prevented",       f"{stats.get('co2_prevented',0):,.0f} t"),
            ("Carbon Credits (VCU)",f"{stats.get('credits',0):,.0f}"),
            ("Est. Market Value",   f"${stats.get('usd_value',0):,.0f}"),
            ("Price per VCU",       "$14.20 (market rate)"),
        ]),
        ("◈ RANGER OPERATIONS", [
            ("Total Dispatches",    str(stats.get('dispatched',0))),
            ("Avg Response Time",   stats.get('avg_response','2h 15m')),
            ("Verification Rate",   f"{stats.get('verify_rate',92)}%"),
            ("Evidence Uploads",    str(stats.get('n_evidence',0))),
        ]),
    ]:
        elems.append(Paragraph(section_title, head_s))
        t_data = []
        for i in range(0, len(rows), 2):
            row = [rows[i][0], rows[i][1]]
            if i + 1 < len(rows):
                row += [rows[i+1][0], rows[i+1][1]]
            else:
                row += ["", ""]
            t_data.append(row)
        st_table = Table(t_data, colWidths=[4.3*cm, 4.3*cm, 4.3*cm, 4.3*cm])
        st_table.setStyle(TableStyle([
            ("FONTNAME",    (0,0),(-1,-1), "Helvetica"),
            ("FONTSIZE",    (0,0),(-1,-1), 8),
            ("TEXTCOLOR",   (0,0),(0,-1),  C_MUTED),
            ("TEXTCOLOR",   (2,0),(2,-1),  C_MUTED),
            ("TEXTCOLOR",   (1,0),(1,-1),  C_LIGHT),
            ("TEXTCOLOR",   (3,0),(3,-1),  C_LIGHT),
            ("FONTNAME",    (1,0),(1,-1),  "Helvetica-Bold"),
            ("FONTNAME",    (3,0),(3,-1),  "Helvetica-Bold"),
            ("BACKGROUND",  (0,0),(-1,-1), C_DARK),
            ("ROWBACKGROUNDS",(0,0),(-1,-1),[C_DARK, C_BG]),
            ("GRID",        (0,0),(-1,-1), 0.5, C_BORDER),
            ("TOPPADDING",  (0,0),(-1,-1), 5),
            ("BOTTOMPADDING",(0,0),(-1,-1),5),
            ("LEFTPADDING", (0,0),(-1,-1), 6),
        ]))
        elems.append(st_table)

    elems.append(Spacer(1, 14))
    elems.append(HRFlowable(width="100%", thickness=1, color=C_GREEN))
    elems.append(Spacer(1, 4))
    elems.append(Paragraph(
        f"ADMRS v4.0 · Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
        ParagraphStyle("ft", fontSize=7, textColor=C_MUTED,
                       fontName="Helvetica", alignment=TA_CENTER)))

    doc.build(elems)
    buf.seek(0)
    return buf.read()
